name: Haskell CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        resolver: [lts-13.11, lts-13.19, lts-14, nightly]

    steps:
    - uses: actions/checkout@v1

    - name: Cache
      uses: actions/cache@v1
      with:
        path: ~/.stack
        key: ${{ runner.os }}-stack-${{ matrix.resolver }}

    - name: Build
      run: |
        stack build --fast --pedantic --ghc-options '-j -ddump-to-file -ddump-hi' --test --no-run-tests --bench --no-run-benchmarks --resolver=${{ matrix.resolver }}

    - name: Test
      run: |
        stack test --fast --pedantic --ghc-options '-j' --resolver=${{ matrix.resolver }}

  # weeder:
  #   runs-on: ubuntu-latest

  #   steps:

  #   - name: Cache
  #     uses: actions/cache@v1
  #     with:
  #       path: ~/.stack
  #       key: weeder

    - name: Weeder
      run: |
        curl -sSL https://raw.github.com/ndmitchell/weeder/master/misc/run.sh | sh -s . --build
